name: Selenium Test with BrowserStack

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t selenium_test_image .

      - name: Run tests in Docker container
        run: docker run -v ${{github.workspace}}:/app selenium_test_image

      - name: Send Email Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./report.html

      - name: Configure Gmail and Send Email
        env:
          GMAIL_USERNAME: ${{secrets.GMAIL_USERNAME}}
          GMAIL_PASSWORD: ${{secrets.GMAIL_PASSWORD}}
          RECIPIENT_EMAIL: kiran.sv@tibilsolutions.com  # Replace with the recipient's email

        run: |
          docker cp send_email_script.py selenium_test_image:/app
          docker exec -e GMAIL_USERNAME=$GMAIL_USERNAME -e GMAIL_PASSWORD=$GMAIL_PASSWORD -e RECIPIENT_EMAIL=$RECIPIENT_EMAIL selenium_test_image python send_email_script.py $GMAIL_USERNAME $GMAIL_PASSWORD $RECIPIENT_EMAIL
