name: Selenium Test with BrowserStack

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t selenium_test_image .

      - name: Run tests in Docker container
        run: docker run -d -v ${{github.workspace}}:/app --name selenium_container selenium_test_image
        # The -d flag runs the container in detached mode (background)

      - name: Wait for container to start
        run: docker ps -f "name=selenium_container" --filter status=running --format "{{.ID}}"

      - name: Execute test script inside container
        run: docker exec -e GMAIL_USERNAME=${{secrets.GMAIL_USERNAME}} -e GMAIL_PASSWORD=${{secrets.GMAIL_PASSWORD}} -e RECIPIENT_EMAIL=kiran.sv@tibilsolutions.com selenium_container python send_email_script.py ${{secrets.GMAIL_USERNAME}} ${{secrets.GMAIL_PASSWORD}} kiran.sv@tibilsolutions.com

      - name: Fetch container logs
        run: docker logs selenium_container
      - name: Send Email Report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ./report.html



