name: Test

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t my-docker-image .

    - name: Run Tests in Docker Container
      run: docker run --rm my-docker-image pytest -v -s --capture=tee-sys ./test.py --html=report.html
